# Generated by Django 2.2.2 on 2019-06-24 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('chapter_number', models.FloatField(unique=True)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('volume', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('published_at', models.DateTimeField(default=None)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.Series')),
            ],
            options={
                'ordering': ('chapter_number',),
            },
        ),
    ]
