# Generated by Django 2.2.2 on 2019-06-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
